---
# Install MooseFS Chunkserver
# Author: Xinyi Chen
# Date: 03/09/2021
# Version: 0.0.1
#-----------------------------------------------------------------------------------------------------------------------------------
# Description: This is a role for installing & Setting up MosseFS Chunkserver.
#-----------------------------------------------------------------------------------------------------------------------------------

- name: Define variables
  set_fact:
    ans_user: "{{ AnsibleUser }}"
    ans_pass: "{{ AnsiblePass }}"
    host_name: "{{ inventory_hostname }}"

- name: Download RPM-GPG-KEY-MooseFS
  get_url:
    url: https://ppa.moosefs.com/RPM-GPG-KEY-MooseFS
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-MooseFS
  become: yes
  vars:
    ansible_become_password: "{{ ans_pass }}"

- name: Download MooseFS-3-el7.repo
  get_url:
    url: http://ppa.moosefs.com/MooseFS-3-el7.repo
    dest: /etc/yum.repos.d/MooseFS.repo
  become: yes
  vars:
    ansible_become_password: "{{ ans_pass }}"

- name: Install moosefs-chunkserver package
  yum:
    name: moosefs-chunkserver
    state: present
  become: yes
  vars:
    ansible_become_password: "{{ ans_pass }}"

- name: Create partition table and partition on target device(s)

- name: Install XFS Progs

- name: Format new partition with XFS

- name: Add entries into /etc/fstab

- name: Create dir for mounting new partition

- name: Mount new partition(s)

- name: Change ownership and access to mountpoints

- name: Add mountpoints to mfshdd.cfg file

- name: Start MooseFS Chunk Server
  ansible.builtin.systemd:
    name: moosefs-chunkserver
    enabled: yes
    state: started
  become: yes
  vars:
    ansible_become_password: "{{ ans_pass }}"
