---
# Install MooseFS Master Server
# Author: Sameer Sinha
# Date: 03/08/2021
# Version: 0.0.1
#-----------------------------------------------------------------------------------------------------------------------------------
# Description: This is a role for installing & Setting up MosseFS Master Server.
#-----------------------------------------------------------------------------------------------------------------------------------

- name: Performing MooseFS Master Server installation & Setup
  hosts: master
  gather_facts: false
  tasks:
    - include_role:
        name: mfsmaster
        tasks_from: install_master
    - include_role:
        name: mfsmaster
        tasks_from: install_master_cli
    - include_role:
        name: mfsmaster
        tasks_from: install_master_cgi
