---
# Install MooseFS Chunk Server
# Author: Xinyi Chen
# Date: 03/09/2021
# Version: 0.0.1
#-----------------------------------------------------------------------------------------------------------------------------------
# Description: This is a role for installing & Setting up MosseFS Chunkserver.
#-----------------------------------------------------------------------------------------------------------------------------------

- name: Performing MooseFS installation
  hosts: chunkserver
  gather_facts: false
  tasks:
    - include_role:
        name: mfschunkserver
        tasks_from: install_chunkserver

