---
# Install MooseFS CGI and CGI Server
# Author: Sameer Sinha
# Date: 03/08/2021
# Version: 0.0.1
#-----------------------------------------------------------------------------------------------------------------------------------
# Description: This is a role for installing MosseFS CGI and CGI Server on Master Server.
#-----------------------------------------------------------------------------------------------------------------------------------

- name: Define variables
  set_fact:
    ans_user: "{{ AnsibleUser }}"
    ans_pass: "{{ AnsiblePass }}"
    host_name: "{{ inventory_hostname }}"

- name: Install Python2 Package
  dnf:
    name: python2
    state: present
  become: yes
  vars:
    ansible_become_password: "{{ ans_pass }}"

- name: Install MooseFS CGI Server on Master Server
  yum:
    name: moosefs-cgiserv
    state: present
  become: yes
  vars:
    ansible_become_password: "{{ ans_pass }}"

- name: Install MooseFS CGI on Master Server
  yum:
    name: moosefs-cgi
    state: present
  become: yes
  vars:
    ansible_become_password: "{{ ans_pass }}"

- name: Start MooseFS Master Server
  ansible.builtin.systemd:
    name: moosefs-cgiserv
    enabled: yes
    state: started
  become: yes
  vars:
    ansible_become_password: "{{ ans_pass }}"
