---
# Install MooseFS CLI
# Author: Sameer Sinha
# Date: 03/08/2021
# Version: 0.0.1
#-----------------------------------------------------------------------------------------------------------------------------------
# Description: This is a role for installing MosseFS CLI on Master Server.
#-----------------------------------------------------------------------------------------------------------------------------------

- name: Define variables
  set_fact:
    ans_user: "{{ AnsibleUser }}"
    ans_pass: "{{ AnsiblePass }}"
    host_name: "{{ inventory_hostname }}"

- name: Install MooseFS CGI Server on Master Server
  apt:
    name: moosefs-cli
    state: present
  become: yes
  vars:
    ansible_become_password: "{{ ans_pass }}"
